on:
  fork:
  push:
    branches: [ master ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this community/project</h1> <strong>Thank you for raising an <strong><em>Issue</em></strong>! Welcome to the the world of open source, where your ideas and contributions are valued and appreciated</strong> <p>If you are willing to involve into open-source you''ve gotten to the right community, to be part of us kindly join us via our <a href="https://discord.gg/c6RhGwcP5b">discord channel</a>, and our <a href="https://github.com/chryz-hub">GitHub organization</a> by raising an <a href="https://github.com/chryz-hub/chryz-hub.github.io/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization">invitational issue</a> and also make the right connections by making this <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/My-PR-Contribution-Practice.md">pull request here</a>.</p><p>Is there anything yet to be understood, please do well to ask us!</p>'
          pr-message: '<h1>It''s great having you contribute to this community/project</h1> <strong>Thank you for creating a <strong><em>Pull Request</em></strong>!  Welcome to the the world of open source, where your ideas and contributions are valued and appreciated</strong> <p>If you are willing to involve into open-source you''ve gotten to the right community, to be part of us kindly join us via our <a href="https://discord.gg/c6RhGwcP5b">discord channel</a>, and our <a href="https://github.com/chryz-hub">GitHub organization</a> by raising an <a href="https://github.com/chryz-hub/chryz-hub.github.io/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization">invitational issue</a> and also make the right connections by making this <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/My-PR-Contribution-Practice.md">pull request here</a>.</p><p>Is there anything yet to be understood, please do well to ask us!</p>'
