name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          skip assign: ${{ github.actor }} 
          reviewers: chryzcodez, Ukpebor
          max-num-of-reviewers: 1
